name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
          cache: "npm"

      - name: Set react application version
        run: echo "REACT_APP_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build react app
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.REACT_APP_VERSION }}
